---
date: "2023-10-26T00:00:00Z"
external_link: ""
image:
  caption: ""
  focal_point: Smart
links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/georgecushen
slides: example
summary: An example of visualization Penguins data using highcharter package.
tags:
- Deep Learning
title: Highcharter
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

This blog post will teach you how to create a highcharter using an open-source dataset called "penguins"

```{r, include=FALSE}

# Instal packages

library(palmerpenguins)
library(highcharter)
library(widgetframe)
```

Let's take a brief at the dataset using the head function
```{r}
head(penguins)
```

Now we can create the scatter plot between bill_length_mm and bill_length_mm
```{r}
scatter_plot  <- na.omit(penguins) %>% 
  hchart("scatter", hcaes(x = bill_length_mm, y = bill_depth_mm, group = species)) %>% 
  hc_add_theme(hc_theme_google()) %>% 
  hc_title(text = "Scatter Plot data Penguins",
           style = list(fontSize = "25px", fontWeight = "bold")) %>% 
  hc_subtitle(text = "By Bill Length (mm) and Bill Depth (mm)",
              style = list(fontSize = "16px")) %>% 
  hc_tooltip(pointFormat = "<b> Bill Length (mm) : </b> {point.x} <br> <b> Bill Depth (mm): </b> {point.y} <br>") %>% 
  hc_credits(enabled = TRUE, text = "@harun_deppalallo")

frameWidget(scatter_plot)
```

