---
date: "2023-10-26T00:00:00Z"
external_link: ""
image:
  caption: ""
  focal_point: Smart
links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/georgecushen
slides: example
summary: Saya mencoba membuat penyebaran covid-19 menggunakan highcharter dan worldgeojson dan menurut saya tampilannya keren!
tags:
- Visualization
title: Map Penyebaran Covid-19
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---

Untuk membuat map penyebaran data, terlebih dahulu memanggil packages yang dibutuhkan

```{r, include=T}

# Instal packages

library(tidyverse)
library(highcharter)
library(widgetframe)
```

Selanjutnya import data covid dan saya menampilkannya menggunakan head() sehingga hanya menampilkan 6 baris pertama saja
```{r}
total_case <- read.csv("covid_data.csv")

head(total_case)
```

Setelah packages dan data sudah siap selanjutnya kita akan membuat visualisasi mapsnya
```{r}
map <- highchart() %>%
  hc_add_series_map(worldgeojson, total_case,
                    value = "total_cases",
                    joinBy = c('name','location'),borderColor = "#FAFAFA") %>% 
  hc_add_theme(hc_theme_ffx()) %>% 
  hc_colors(c("darkgreen", "darkred")) %>%
  hc_colorAxis(stops = color_stops()) %>%
  hc_title(text = "Map Penyebaran Covid-19") %>% 
  hc_subtitle(text = "Tanggal Data : 2022-01-01") %>% 
  hc_credits(enabled = T, text = "Made by Harun Deppalallo")

frameWidget(map)
```

